name: CI
on: 
  workflow_dispatch:
    inputs:
      greeting_name:
        description: "Person to greet"
        default:  "Homee"
        required: true
  pull_request:
    types:
      - "labeled"
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # - name: Run a one-line script
      #   run: echo hello, workflow
      # - name: Run a multi-line script
      #   run: |
      #     echo add other actions to build,
      #     echo test, and deploy your project
      # - name: hello-action
      #   uses: ./.github/actions/hello-world    
      #   with:
      #     firstGreeting: "Learning Lab User"
      #     thirdGreeting: "Birder"

      # - name: meow
      #   uses: ./.github/actions/cat-facts  
      #   id: cat

      - name: create-issue
        uses: ./.github/actions/issue-maker
        with:
          repoToken: ${{secrets.GITHUB_TOKEN}}
          catFact: ${{steps.cat.outputs.fact}}
          issueTitle: "a cat fact for you"    

